### ISSUE TITLE
👍👍👍 Hey Dude! This is an absolutely DOPE Repo! Keep It UP!!!!!!

### ISSUE THREAD

**Issue by Ryan-Ray-Offical** [RemyK888/discord-together#1]
Hey This is like the best git repo i ever seen!

Thank You!

Ik that you just added it lol, but can you like put it in the bukkit list that you add Netflix so me and my friends can netflix and chill? c: Thank you and btw

This is a dope project, keep it up!!

**Comment by RemyK888** [comment]
Thanks a lot @Ryan-Ray-Offical , I'll see what I can do about it ! 
In the meantime you can join my Discord server. I will close this issue tomorrow if you have no further questions.
Sincerely, RemyK
