### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: An error occured while starting Youtube together !

### ISSUE THREAD

**Issue by Dxngaa** [RemyK888/discord-together#12]
-------------------

I have been getting this error for a few days without having touched any of the code. "UnhandledPromiseRejectionWarning: Error: An error occured while starting Youtube together !"

-------------------

- Information:
1.  Error: UnhandledPromiseRejectionWarning: Error: An error occured while starting Youtube together !
2. Node Version: 14.17.3
3. DiscordTogether Version: ^1.1.14

-------------------

`(node:3781) UnhandledPromiseRejectionWarning: Error: An error occured while starting Youtube together !
    at DiscordTogether.createTogetherCode (/home/runner/Zanix-Bot/node_modules/discord-together/src/DiscordTogether.js:95:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3781) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by RemyK888** [comment]
Hey, join my discord server to be able to talk easier 
https://discord.gg/UBUSgw4

**Comment by Dxngaa** [comment]
Thanks.

**Comment by Dxngaa** [comment]
Thanks.
