### ISSUE TITLE
more like a question rather than an issue

### ISSUE THREAD

**Issue by Prabesh01** [RemyK888/discord-together#13]
so is there anyway yet to:

i) enable fullscreen. not the discord's fullscreen but youtube's itself. it says full screen unavailable. May be some sorta user script to bypass it?

ii) i dont think this is available yet but how to give access to only selected person to control and make other able to view only.

ii) Is there a way to keep the yt together going on even though I leave the VC so than i could continue it later. May be adding a bot to the activity so the activity goes on or sth else.

iv) add playlist instead of a video one by one

I know most of these are not directly possible so I am asking for some workaround methods which can help upto some extent.

Thank you.

**Comment by RemyK888** [comment]
Hello, everything you ask is unfortunately impossible, I invite you to join my Discord server to have more information, and to talk there more at ease https://discord.gg/YNYaeErWRp
Can I close this issue?
~ RemyK

**Comment by Prabesh01** [comment]
sure

Thank you.
