### ISSUE TITLE
DeprecationWarning messageCreate

### ISSUE THREAD

**Issue by Ryckie** [RemyK888/discord-together#18]
After I start the bot and I send a text message in any channel. I get this error.

`(node:9360) DeprecationWarning: The message event is deprecated. Use messageCreate instead
(Use `node --trace-deprecation ...` to show where the warning was created)
`

**Comment by Scarner56** [comment]
Hello;

I thiking you are using discord.js v13
In v13 message event is changed with mesaageCreate
You need to make your message event's messageCreate

That's it

**Comment by DaSussy** [comment]
On Discord.js 13 the message event changed to `messageCreate`

**Comment by Whirl21** [comment]
> On Discord.js 13 the message event changed to `messageCreate`
> 
> Also, which discord-together version are you using?

Yes and the message event was deprecated so you would continue to recieve the warning until you switch to messageCreate (takes one line to switch)

**Comment by Ryckie** [comment]
> > On Discord.js 13 the message event changed to `messageCreate`
> > Also, which discord-together version are you using?
> 
> Yes and the message event was deprecated so you would continue to recieve the warning until you switch to messageCreate (takes one line to switch)

@DaSussy I used the commands from the readme.md.

I have been trying to change to messageCreate. But it did gave me other errors. I found multiple places to change it. But you say its just one line. I dont really know what exactly I have to change and where. Can you guide me with the filename or place I need to change this please?

**Comment by DaSussy** [comment]
> > > On Discord.js 13 the message event changed to `messageCreate`
> 
> > > Also, which discord-together version are you using?
> 
> > 
> 
> > Yes and the message event was deprecated so you would continue to recieve the warning until you switch to messageCreate (takes one line to switch)
> 
> 
> 
> @DaSussy I used the commands from the readme.md.
> 
> 
> 
> I have been trying to change to messageCreate. But it did gave me other errors. I found multiple places to change it. But you say its just one line. I dont really know what exactly I have to change and where. Can you guide me with the filename or place I need to change this please?

do you have a command handler?

**Comment by Ryckie** [comment]
@DaSussy I dont know what that is. I used cmd to install the requirements. Then started the bot also thru the same cmd window.

**Comment by DaSussy** [comment]
> @DaSussy I dont know what that is. I used cmd to install the requirements. Then started the bot also thru the same cmd window.


change client.on("message") to client.on("messageCreate")

**Comment by RemyK888** [comment]
Yeah, sorry, I'm going to update the code example

**Comment by dylanjamesdev** [comment]
Don't change this, it would break v12 users..... its depreciated so it would still work

**Comment by Whirl21** [comment]
hey meant to change it in the code example

**Comment by RemyK888** [comment]
Or maybe can I make 2 code example ?
V12 and V13 ?
