### ISSUE TITLE
The client is not necesary as a param

### ISSUE THREAD

**Issue by MontejoJorge** [RemyK888/discord-together#23]
I don't know whether to classify this as unexpected behavior or as a error in the documentation, or even if you were already aware of this behavior.

I think it is unnecessary to initialize the constructor with the discord js client, when discord-together only needs the bot token for the post request.

The way I do it:
```js
const { DiscordTogether } = require('discord-together');

const discordTogether = new DiscordTogether({ token: process.env.DISCORD_TOKEN });
```
Using command handling or event handling is simpler for me to create it this way, so I avoid having discord code together outside of the command I use it in.

**Comment by RemyK888** [comment]
Indeed, your code is valid, there are several methods to use this package, each one chooses its way to use it, but for more simplicity, I do not intend to change the params or the readme

If you have no more questions, I can close this issue.

~ RemyK

**Comment by MontejoJorge** [comment]
Roger that, if you ever need help with a function, please let me know.

Bests,
Jorge.
