### ISSUE TITLE
Application ID?

### ISSUE THREAD

**Issue by DeathGOD7** [RemyK888/discord-together#25]
Is the youtube and youtube dev old Youtube Together or new one branded as "Watch Together"?
If you could, can you provide it both if missing?
Ty for it.

**Comment by RemyK888** [comment]
The 2 identifiers are new, if you want the old version, you just have to download an old version.

If you have no more questions, can I close this issue?

~ RemyK

**Comment by DeathGOD7** [comment]
> The 2 ids are new, if you want the old version, you just have to download an old version.
> 
> If you have no more questions, can I close this issue?
> 
> ~ RemyK

Can you provide link or ids of them? Thank You

**Comment by RemyK888** [comment]
Download older versions of the project or look at previous versions on Github, all IDs are commented
