### ISSUE TITLE
New Activity: Checkers in the Park

### ISSUE THREAD

**Issue by Cannicide** [RemyK888/discord-together#37]
About an hour ago, Discord put out a new "Checkers in the Park" activity similar to the existing "Chess in the Park." I believe I have retrieved the activity's ID, so it can now be added to this package.

Activity ID: `832013003968348200`

**Comment by BIOLOGY-SCIENCE** [comment]
> About an hour ago, Discord put out a new "Checkers in the Park" activity similar to the existing "Chess in the Park." I believe I have retrieved the activity's ID, so it can now be added to this package.
> 
> Activity ID: `832013003968348200`

The first thing for me was to come here to see any updates for the package regarding the checkers ID, thank you so much for updating.
And btw, how did you get the ID ? Like did they post it somewhere in the channels ?

**Comment by Cannicide** [comment]
I don't think they post the IDs anywhere, as these activities aren't actually meant to be used anywhere outside of the Discord Games Lab server at the moment. As for how I did it, I devised a trick to retrieve the ID from the icon of the activity. You'll notice that if you hover over a voice channel when people are playing a specific activity, it will show what activity they are playing along with its icon. I figured it would make sense that the ID of the activity would be part of that activity's icon URL. Sure enough, the URL of app icons follows the following format:

`https://cdn.discordapp.com/app-assets/<app-id>/<asset-id>.png`

So from the icon's URL, you can obtain the app's ID. Assuming, of course, that people are playing the activity in the Discord Games Lab server. I used the dev console (i.e. "inspect element") to obtain the URL of the icon, which was the following:

`https://cdn.discordapp.com/app-assets/832013003968348200/904775325026750464.png`

And consequently extracted the activity's ID from there.

**Comment by BIOLOGY-SCIENCE** [comment]
@Cannicide 
I was literally about to tell you that I found out with this same exact way 😂
Anyways thank you 😃

**Comment by RemyK888** [comment]
Thank you very much, I'll update the package today !
