### ISSUE TITLE
New Activities

### ISSUE THREAD

**Issue by kamiya10** [RemyK888/discord-together#39]
`879864070101172255` sketchyartist
`832012854282158180` putts
`763133495793942528` pokerdev
`878067427668275241` doodlecrewdev
`879864010126786570` wordsnackdev
`879864104980979792` sketchyartistdev
`891001866073296967` decodersdev
`832012586023256104` CG 2 Dev
`832012682520428625` CG 3 Dev
`832013108234289153` CG 4 Dev

![image](https://user-images.githubusercontent.com/58339640/140905983-2c723fcc-b3ac-4fbd-a907-74c307f5b0c6.png)

IDs are from Inspector Tool (`Ctrl` + `Shift` + `I`)
`activity-popout-{ID}`
![image](https://user-images.githubusercontent.com/58339640/140906533-d94f35fd-8efe-481b-8d4e-70d9c1106d8f.png)

**Comment by RemyK888** [comment]
Thank you very much.
I'll update this evening

**Comment by kamiya10** [comment]
Putts have changed into Putt Party `763133495793942528`
![image](https://user-images.githubusercontent.com/58339640/141484226-00d8c67a-dc73-466b-a016-724cc009296c.png)

**Comment by RemyK888** [comment]
Updated
