### ISSUE TITLE
Code example not working

### ISSUE THREAD

**Issue by GeekCornerGH** [RemyK888/discord-together#41]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
Not applicable
- [ ] I checked the documentation and found no answer
Not applicable
- [ ] I checked to make sure that this issue has not already been filed
Not aplicable
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected behavior

Please describe the behavior you are expecting
I expect your code example to work.

# Current behavior

What is the current behavior?
It wont work

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create Discord bot, in main file copy and paste in main file the [example](https://github.com/RemyK888/discord-together#-code-example)
2. Install all dependancies
3. Run main file
## Context
In Discord.JS 13, messageCreate replaces message event, so I assume your example is for Discord.JS 13. You need to declare Client intents, else, it wont work

**Comment by Scoooolzs** [comment]
The code is missing intents. If you want the right one, there is the code:

```js
const Discord = require('discord.js');
const client = new Discord.Client({ intents: ["GUILDS", "GUILD_MESSAGES", "GUILD_VOICE_STATES"] }); // Leave blank for Discord.js v12

const { DiscordTogether } = require('discord-together');

client.discordTogether = new DiscordTogether(client);

const prefix = "!"; // Change the prefix if you want.

client.on('messageCreate', (message) => { // 'message' for Discord.js v12
    if (message.author.bot || !message.content.startsWith(prefix)) return;
    
    let args = message.content.trim().split(/ +/);
    const commandName = args[0].slice(prefix.length).toLowerCase();

    if (commandName === "start") {
        if(message.member.voice.channel) {
             client.discordTogether.createTogetherCode(message.member.voice.channel.id, 'doodlecrew' /* <- Change this if you dont want doodlecrew*/).then((invite) => {
                return message.reply(`${invite.code}`);
            });
        };
    };
});

client.login('5EcR3t.b0T.T0k3N.D0nT5h4rETh3t0KeN0fTh3B0t');
```

> Note: The code is better than the example.

**Comment by DraftProducts** [comment]
> The code is missing intents. If you want the right one, there is the code:
> 
> 
> 
> ```js
> 
> const Discord = require('discord.js');
> 
> const client = new Discord.Client({ intents: ["GUILDS", "GUILD_MESSAGES", "GUILD_VOICE_STATES"] }); // Leave blank for Discord.js v12
> 
> 
> 
> const { DiscordTogether } = require('discord-together');
> 
> 
> 
> client.discordTogether = new DiscordTogether(client);
> 
> 
> 
> const prefix = "!"; // Change the prefix if you want.
> 
> 
> 
> client.on('messageCreate', (message) => { // 'message' for Discord.js v12
> 
>     if (message.author.bot || !message.content.startsWith(prefix)) return;
> 
>     
> 
>     let args = message.content.trim().split(/ +/);
> 
>     const commandName = args[0].slice(prefix.length).toLowerCase();
> 
> 
> 
>     if (commandName === "start") {
> 
>         if(message.member.voice.channel) {
> 
>              client.discordTogether.createTogetherCode(message.member.voice.channel.id, 'doodlecrew' /* <- Change this if you dont want doodlecrew*/).then((invite) => {
> 
>                 return message.reply(`${invite.code}`);
> 
>             });
> 
>         };
> 
>     };
> 
> });
> 
> 
> 
> client.login('5EcR3t.b0T.T0k3N.D0nT5h4rETh3t0KeN0fTh3B0t');
> 
> ```
> 
> 
> 
> > Note: The code is better than the example.

*Hope that you token is invalid...*

**Comment by Scoooolzs** [comment]
> > The code is missing intents. If you want the right one, there is the code:
> > ```js
> > const Discord = require('discord.js');
> > 
> > const client = new Discord.Client({ intents: ["GUILDS", "GUILD_MESSAGES", "GUILD_VOICE_STATES"] }); // Leave blank for Discord.js v12
> > 
> > 
> > 
> > const { DiscordTogether } = require('discord-together');
> > 
> > 
> > 
> > client.discordTogether = new DiscordTogether(client);
> > 
> > 
> > 
> > const prefix = "!"; // Change the prefix if you want.
> > 
> > 
> > 
> > client.on('messageCreate', (message) => { // 'message' for Discord.js v12
> > 
> >     if (message.author.bot || !message.content.startsWith(prefix)) return;
> > 
> >     
> > 
> >     let args = message.content.trim().split(/ +/);
> > 
> >     const commandName = args[0].slice(prefix.length).toLowerCase();
> > 
> > 
> > 
> >     if (commandName === "start") {
> > 
> >         if(message.member.voice.channel) {
> > 
> >              client.discordTogether.createTogetherCode(message.member.voice.channel.id, 'doodlecrew' /* <- Change this if you dont want doodlecrew*/).then((invite) => {
> > 
> >                 return message.reply(`${invite.code}`);
> > 
> >             });
> > 
> >         };
> > 
> >     };
> > 
> > });
> > 
> > 
> > 
> > client.login('5EcR3t.b0T.T0k3N.D0nT5h4rETh3t0KeN0fTh3B0t');
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > Note: The code is better than the example.
> 
> _Hope that you token is invalid..._

lol

**Comment by RemyK888** [comment]
Thank you very much, I'll update the package
