### ISSUE TITLE
Check if all users left an Activity

### ISSUE THREAD

**Issue by FreshImmuc** [RemyK888/discord-together#47]
Hey, how do I make the bot do something when ALL users left it? (If no one is in it)

If this is not possible, are there any alternatives?

**Comment by BIOLOGY-SCIENCE** [comment]
There is nothing to do with this package which can do what you expect.
<br>
You would have to code your bot by your own which would listen for `voiceStateUpdate` or maybe in other ways, by which you could get the members who join the voice channel and leave them.

**Comment by FreshImmuc** [comment]
Hmm okay thank you! Really helped me!
