### ISSUE TITLE
Add New Activity: Ocho

### ISSUE THREAD

**Issue by Cannicide** [RemyK888/discord-together#48]
Activity ID: `832025144389533716`

![Ocho](https://cdn.discordapp.com/app-icons/832025144389533716/6fe6e3dda7657b83758693205a833aa1.webp?size=56&keep_aspect_ratio=false)

**Comment by FreshImmuc** [comment]
+1

**Comment by RemyK888** [comment]
Hey, thanks for your help, this activity has been added in version **1.3.3**
`npm i discord-together@latest`
