### ISSUE TITLE
youtube dont work?

### ISSUE THREAD

**Issue by Salem-2** [RemyK888/discord-together#55]
if (message.content.toLowerCase() === 'playYT') {
        if(message.member.voice.channel) {
            client.discordTogether.createTogetherCode(message.member.voice.channel.id, 'youtubeDev').then(async invite => {
                return message.channel.send(`${invite.code}`);
            });
        };
    };

when sending playYT command the bot dont reply and there is no error and other games work fine i also tried normal youtube and also didnt work

**Comment by Scarner56** [comment]
i thihk you need 1 level boost on the server to use it

**Comment by ShambaC** [comment]
> i thihk you need 1 level boost on the server to use it

boost is not required for youtube.

**Comment by Salem-2** [comment]
> > i thihk you need 1 level boost on the server to use it
> 
> boost is not required for youtube.

even tho boost is required the server is lvl 3 already so its not about boost

**Comment by Scarner56** [comment]
try the youtube application not youtubeDev
