### ISSUE TITLE
Sketch Heads no worky

### ISSUE THREAD

**Issue by Itz-Hyperz** [RemyK888/discord-together#59]
Sketch Heads doesn't work...

NodeJS V16.13.2
Module V1.3.3

doodle crew works, but tells you to go to sketch heads, and sketch heads just doesn't work...

**Comment by RemyK888** [comment]
Hello, check the boost level of your server.
The platform you are using Discord on can also interfere.

If not, you can always send an email to Discord support for more information.

*(Sorry for the long response time)*
