### ISSUE TITLE
Invalid invite url

### ISSUE THREAD

**Issue by L0SER8228** [RemyK888/discord-together#8]
```js
const { MessageEmbed } = require("discord.js");

module.exports = {
  name: "chess",
  description: "Make a Chess voice channel.",
  async execute(bot, message) {
    const voice = message.member?.voice;

    if (!voice?.channel)
      return message.channel.send( "❌ You have to join a voice channel first.");

    if (!voice?.channel.viewable)
      return message.channel.send("❌ I need **\`VIEW_CHANNEL\`** permission.");

    const invite = await bot.discordTogether.createTogetherCode(voice.channelID, "chess").catch(console.error);

    const embed = new MessageEmbed()
      .setDescription(`[Click here the invite link to join it.](${invite.code})`)

    return message.channel.send(embed);
  },
};
```
This code was working fine some days ago. But now I'm getting this link 
https://discord.com/invite/50013
I tried with many voice channel , and with all the activities . I'm getting only this link

**Comment by RemyK888** [comment]
hey, i'll check your error tomorrow, maybe can you join my Discord server to speak more simply !
https://discord.gg/GE8fmJqTZm

**Comment by dinosaurioh** [comment]
This error is solved in [this pull request](https://github.com/RemyK888/discord-together/pull/7), actually "50013" is part of an error code from Discord and not actually a valid invite link.

**Comment by L0SER8228** [comment]
When it'll fix

**Comment by JimmyTheRustler** [comment]
I've had a similar issue where I get 50035 as the invite link. However when a user switches voice channels and then issues the command it seems to work as intended for some reason.

**Comment by RemyK888** [comment]
Hey @JimmyTheRustler can you explain how you solved this error ?

**Comment by JimmyTheRustler** [comment]
I dont know if I would say solved but I've found that when a user joins a discords voice chat for the first time and tries watching YouTube together they receive a 50035 invite, but then if they move to another voice channel and run the command it works and gets them a correct invite link. I'm not sure if the issue is to do with discord-together or my bot not being able to return the users voice channel ID when they first join a voice channel for the first time.

**Comment by L0SER8228** [comment]
No

> I dont know if I would say solved but I've found that when a user joins a discords voice chat for the first time and tries watching YouTube together they receive a 50035 invite, but then if they move to another voice channel and run the command it works and gets them a correct invite link. I'm not sure if the issue is to do with discord-together or my bot not being able to return the users voice channel ID when they first join a voice channel for the first time.

No , it was working fine till some days ago

**Comment by apurv-r** [comment]
Error code 50013 is specified by Discord as "You lack permissions to perform that action". Perhaps check your bot's permissions for creating invites or accessing that particular VC?

[Here's the Discord Docs for error codes](https://discord.com/developers/docs/topics/opcodes-and-status-codes)
